"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowRight,Box,Check,ChevronDown,CircleAlert,Download,FileText,Globe2,Image as ImageIcon,Palette,RotateCw,ShieldCheck,Sparkles,Upload} from "lucide-react";

const marketCopy={美国:{tag:"清晰表达 · 强品牌识别",title:"把文化故事讲得直接、易懂",copy:"突出茶叶产地、自然风味与手工工艺，用更明确的卖点层级帮助消费者快速理解。",labels:["英文文化故事","净含量信息区","产品卖点正面化"]},日本:{tag:"克制留白 · 强材质感",title:"让传统文化以更含蓄的方式出现",copy:"降低装饰密度，强调纸张、细节与秩序感，以简洁叙事呈现茶叶的地域与工艺。",labels:["日文市场表达","信息层级收敛","纹样局部化"]}};
const steps=[["01","上传产品","上传一张清晰的产品正面图，或直接使用平台提供的茶叶示例。"],["02","选择市场","填写产品定位，选择美国或日本，系统建立市场适配方向。"],["03","匹配非遗","依据品类、寓意和使用场景，推荐纹样、传统色与文化表达。"],["04","生成方案","一次获得包装视觉、文化文案、标签提示与3D展示方向。"]];
const patterns=[["折枝新生纹","植物构成 · 概念纹样","生长、丰收与延续","适合天然茶叶与地方农产品"],["锦羽回环纹","织绣节律 · 概念纹样","守护、联结与祝愿","适合节庆礼赠与系列包装"],["花窗叠影纹","窗棂几何 · 概念纹样","秩序、圆满与相聚","适合高端礼盒与品牌延展"]];

export default function Home(){
 const fileRef=useRef<HTMLInputElement>(null);const[fileName,setFileName]=useState("");const[market,setMarket]=useState<"美国"|"日本">("美国");const[heroView,setHeroView]=useState<"正面"|"侧面"|"360°">("正面");const[heroOutput,setHeroOutput]=useState(0);const[style,setStyle]=useState("折枝新生纹");const[stage,setStage]=useState<"idle"|"loading"|"done">("idle");const[loadStep,setLoadStep]=useState(0);const[plan,setPlan]=useState(0);const[openFaq,setOpenFaq]=useState(0);const[compare,setCompare]=useState(50);const[activeCap,setActiveCap]=useState(0);const[revenueStep,setRevenueStep]=useState(0);const info=marketCopy[market];const heroOutputs=[[Palette,"包装视觉","3套方向","生成适配品类与市场的视觉方向"],[FileText,"文化文案","双语转译","将纹样寓意转成海外品牌故事"],[CircleAlert,"标签提示","风险线索","梳理信息区域与潜在合规问题"],[Box,"3D预览","多视角","检查正面、侧面与整体应用效果"]] as const;const loadingLabels=["分析产品特征","匹配目标市场","推荐非遗纹样","生成完整方案"];const progress=useMemo(()=>stage==="loading"?loadingLabels[loadStep]:stage==="done"?`已生成 ${market}市场方案`:"使用茶叶示例，无需上传",[stage,market,loadStep]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add("is-visible")),{threshold:.12});document.querySelectorAll(".section,.creator-wrap,.human-section,.closing").forEach(el=>{el.classList.add("reveal");observer.observe(el)});return()=>observer.disconnect()},[]);
 function generate(){setStage("loading");setLoadStep(0);[420,820,1220].forEach((ms,i)=>window.setTimeout(()=>setLoadStep(i+1),ms));window.setTimeout(()=>{setStage("done");document.querySelector("#result")?.scrollIntoView({behavior:"smooth"})},1650)}
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span>纹</span><b>纹脉<small>WENMAI</small></b></a><nav><a href="#why">产品能力</a><a href="#flow">设计流程</a><a href="#market">市场适配</a><a href="#patterns">非遗纹样库</a><a href="#business">商业模式</a></nav><button className="solid compact" onClick={()=>document.querySelector("#creator")?.scrollIntoView({behavior:"smooth"})}>体验工作台</button></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="kicker">非遗包装 AI 设计平台</p><div className="hero-promise"><ImageIcon/>一张产品图<span>→</span>一套出海包装方案</div><h1>让中国非遗<br/>成为产品走向世界的<br/><span>品牌语言。</span></h1><p className="lead">上传产品并选择目标市场，一次获得包装视觉、文化文案、标签提示与 3D 展示方案。</p><div className="hero-output-grid">{heroOutputs.map(([Icon,title,value],i)=><button key={title} className={heroOutput===i?"active":""} onClick={()=>{setHeroOutput(i);setHeroView(i===2?"侧面":i===3?"360°":"正面")}}><Icon/><span><b>{title}</b><small>{value}</small></span></button>)}</div><div className="hero-actions"><button className="solid" onClick={()=>document.querySelector("#creator")?.scrollIntoView({behavior:"smooth"})}>立即体验茶叶示例 <ArrowRight/></button><button className="hero-link" onClick={()=>document.querySelector("#market")?.scrollIntoView({behavior:"smooth"})}>查看双市场对比 <ArrowRight/></button></div><div className="proof"><span><Check/>一次生成 4 类成果</span><span><Check/>美国／日本双市场适配</span><span><Check/>纹样来源与授权可追溯</span></div></div><div className={`hero-workbench view-${heroView==="正面"?"front":heroView==="侧面"?"side":"spin"}`}><img src="/wenmai-hero-export-transformation.png" alt={`${market}市场茶叶包装${heroView}预览`}/><div className="hero-market-switch" aria-label="选择首屏预览市场"><button className={market==="美国"?"active":""} onClick={()=>setMarket("美国")}>美国版</button><button className={market==="日本"?"active":""} onClick={()=>setMarket("日本")}>日本版</button></div><div className="hero-ai-note"><span><Sparkles/></span><div><small>{heroOutput===0?"AI 市场适配建议":heroOutputs[heroOutput][1]}</small><b>{heroOutput===0?(market==="美国"?"强化品牌识别与核心卖点":"减少装饰密度，突出材质留白"):heroOutputs[heroOutput][2]}</b><p>{heroOutput===0?(market==="美国"?"英文故事 · 净含量区域 · 正面卖点":"日文表达 · 信息收敛 · 纹样局部化"):heroOutputs[heroOutput][3]}</p></div></div><div className="hero-view-switch">{(["正面","侧面","360°"] as const).map(x=><button key={x} className={heroView===x?"active":""} onClick={()=>setHeroView(x)}>{x==="360°"&&<RotateCw/>}{x}</button>)}</div><div className="hero-flow">{[[Upload,"上传产品"],[Globe2,"选择市场"],[Palette,"匹配非遗"],[Box,"完整方案"]].map(([Icon,label],i)=><div key={label as string}><span><Icon/></span><small>0{i+1}</small><b>{label as string}</b>{i<3&&<ArrowRight/>}</div>)}</div></div></section>
  <section className="creator-wrap" id="creator"><div className="creator-intro"><p className="kicker light">TRY THE WORKFLOW</p><h2>从一款茶叶开始，生成它面向世界的新表达</h2><p>当前为结构化概念原型。使用预设结果演示完整产品路径，不代表真实AI模型已经接入。</p></div><div className="creator-panel"><button className="upload" onClick={()=>fileRef.current?.click()}><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>setFileName(e.target.files?.[0]?.name||"")}/>{fileName?<><ImageIcon/><b>{fileName}</b><small>点击更换产品图片</small></>:<><Upload/><b>上传你的产品图片</b><small>或直接使用“地方春茶”示例</small></>}</button><Field label="产品名称"><input defaultValue="云岭春茶"/></Field><Field label="目标市场"><div className="segmented"><button className={market==="美国"?"active":""} onClick={()=>setMarket("美国")}>美国市场</button><button className={market==="日本"?"active":""} onClick={()=>setMarket("日本")}>日本市场</button></div></Field><Field label="品牌调性"><select defaultValue="自然高端"><option>自然高端</option><option>年轻现代</option><option>节庆礼赠</option></select></Field><button className="solid generate" onClick={generate} disabled={stage==="loading"}>{stage==="loading"?<><RotateCw className="spin"/>正在生成完整方案</>:<><Sparkles/>生成出海包装方案</>}</button><p className="status-line"><span className={stage==="done"?"done":""}/>{progress}</p></div></section>
  <section className="section capability-story" id="why"><Head index="01" kicker="WHY WENMAI" title="不止生成一张好看的图" copy="从一张产品图，生成一套可理解、可检查、可展示的出海包装方案。"/><div className="capability-stage"><div className="capability-visual"><img src={["/wenmai-hero-export-transformation.png","/hero-digital.webp","/wenmai-us-japan-comparison.png","/hero-packaging.webp"][activeCap]} alt={["茶叶包装视觉方案","双语文化文案设计过程","包装标签与市场风险提示","茶叶包装3D预览"][activeCap]}/><div className="visual-badge"><small>完整方案 · 0{activeCap+1}</small><b>{["包装视觉方向","文化故事转译","标签风险提示","三维包装预览"][activeCap]}</b></div><div className="view-switch"><button className={activeCap===0?"active":""} onClick={()=>setActiveCap(0)}>正面</button><button className={activeCap===2?"active":""} onClick={()=>setActiveCap(2)}>背面</button><button className={activeCap===3?"active":""} onClick={()=>setActiveCap(3)}>3D</button></div></div><div className="capability-list">{[[Palette,"包装视觉","根据品类、品牌调性与目标市场生成多套包装方向。"],[FileText,"文化文案","把纹样寓意转译成海外消费者能够理解的品牌故事。"],[CircleAlert,"标签提示","呈现信息区域与潜在风险，为后续专业审核提供线索。"],[Box,"3D预览","检查包装正面、侧面和背面的整体应用效果。"]].map(([Icon,title,copy]:any,i)=><button key={title} className={activeCap===i?"active":""} onMouseEnter={()=>setActiveCap(i)} onClick={()=>setActiveCap(i)}><span><Icon/><em>0{i+1}</em></span><div><h3>{title}</h3><p>{copy}</p></div><ArrowRight/></button>)}</div></div></section>
  <section className="section flow" id="flow"><Head index="02" kicker="ONE WORKFLOW" title="四步完成一套文化包装方案" copy="每一步只要求用户做清晰选择，把复杂的设计沟通转化为可理解、可比较的结果。"/><div className="step-grid">{steps.map((x,i)=><article key={x[0]}><div className="step-top"><span>{x[0]}</span><small>STEP</small></div><Media label={["产品上传示意图","市场选择界面图","非遗纹样推荐图","完整方案输出图"][i]} detail="建议4:3界面截图或产品操作示意"/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="market-section" id="market"><div className="section market-inner"><Head index="03" kicker="MARKET ADAPTATION" title="同一款茶叶，不同市场需要不同表达" copy="拖动分界线直观比较两个市场的包装方向；也可切换市场查看对应文案和标签变化。"/><div className="market-tabs"><button className={market==="美国"?"active":""} onClick={()=>setMarket("美国")}>美国市场方案</button><button className={market==="日本"?"active":""} onClick={()=>setMarket("日本")}>日本市场方案</button></div><div className="compare-slider"><div className="compare-side usa"><b>美国版包装图</b><span>需要：品牌识别强、卖点清晰的茶叶包装</span></div><div className="compare-side japan" style={{clipPath:`inset(0 0 0 ${compare}%)`}}><b>日本版包装图</b><span>需要：克制留白、强调材质的茶叶包装</span></div><div className="compare-handle" style={{left:`${compare}%`}}><span>↔</span></div><input aria-label="拖动比较美国版和日本版包装" type="range" min="12" max="88" value={compare} onChange={e=>setCompare(Number(e.target.value))}/><small className="drag-tip">拖动对比两种市场表达</small></div><div className="market-stage compact-stage"><div className="market-copy"><span>{info.tag}</span><h3>{info.title}</h3><p>{info.copy}</p><ul>{info.labels.map(x=><li key={x}><Check/>{x}</li>)}</ul><button className="line-btn" onClick={()=>setMarket(market==="美国"?"日本":"美国")}>切换查看{market==="美国"?"日本":"美国"}版 <ArrowRight/></button></div><div className="market-facts"><div><strong>01</strong><span>包装构图同步变化</span></div><div><strong>02</strong><span>文化文案自动转译</span></div><div><strong>03</strong><span>标签布局随市场调整</span></div></div></div></div></section>
  <section className="section patterns" id="patterns"><Head index="04" kicker="PATTERN INTELLIGENCE" title="纹样不是装饰，而是有依据的设计选择" copy="平台说明纹样从哪里来、表达什么、为什么适合当前产品与市场，并提示商业授权边界。"/><div className="pattern-grid">{patterns.map((p,i)=><article className={style===p[0]?"selected":""} key={p[0]} onClick={()=>setStyle(p[0])}><Media label={`非遗纹样图 ${i+1}`} detail="需要高清纹样局部与应用延展，建议1:1"/><div><small>{p[1]}</small><h3>{p[0]}</h3><p>{p[2]}</p><em>{p[3]}</em><footer><span><ShieldCheck/>授权信息待完善</span><button>选择纹样</button></footer></div></article>)}</div></section>
  <section className="result section" id="result"><Head index="05" kicker="DESIGN OUTPUT" title="一套方案，覆盖从视觉到落地的信息" copy={`当前选择：云岭春茶 · ${market}市场 · ${style}`}/><div className={`result-shell ${stage==="loading"?"loading":""}`}><div className="result-main"><div className="result-toolbar"><span>{stage==="done"?"方案已生成":"预设方案预览"}</span><button onClick={()=>alert("概念原型：后续将在这里导出方案包。") }><Download/>导出方案</button></div><Media label="包装完整效果图 / 3D可旋转预览" detail="需要茶叶盒正面、侧面、背面及应用场景；建议16:10"/><div className="plan-tabs">{["方案 A","方案 B","方案 C"].map((x,i)=><button className={plan===i?"active":""} onClick={()=>setPlan(i)} key={x}>{x}<span>需要方案缩略图</span></button>)}</div></div><aside><span className="report-tag">文化适配报告</span><h3>{style}</h3><p>以“生长与丰收”为核心寓意，适合天然茶叶和地方农产品。当前推荐降低纹样密度，让文化元素服务于品牌识别。</p><div className="report-block"><small>目标市场建议</small><b><Globe2/>{market}</b><p>{info.copy}</p></div><div className="report-block warning"><small>风险提示</small><p>本页面为概念演示。真实商用前需进一步确认纹样来源、授权范围及目标市场标签法规。</p></div><button className="line-btn wide">查看完整方案包 <ArrowRight/></button></aside></div></section>
  <section className="human-section"><div><p className="kicker light">AI + HUMAN CRAFT</p><h2>AI给出方向，设计师完成生产级交付</h2><p>用户选中方案后，可继续完成版式精修、印前检查、系列包装延展和生产文件整理。</p><button className="gold">了解人工精修 <ArrowRight/></button></div><Media label="AI与设计师协同过程图" detail="需要设计稿批注、前后版本或设计师工作场景；建议4:3"/></section>
  <section className="business-dark" id="business"><div className="section business"><Head index="06" kicker="BUSINESS MODEL" title="从生成，到授权，再到专业交付" copy="每一次点击，都对应产品价值与商业收入的递进。"/><div className="journey"><div className="journey-visual"><img src={["/wenmai-hero-export-transformation.png","/hero-archive.webp","/wenmai-ai-human-workflow.png"][revenueStep]} alt={["AI包装方案生成","纹样档案与商业授权","设计师完成包装精修"][revenueStep]}/><div className="journey-caption"><small>0{revenueStep+1} / 03</small><h3>{["先快速生成设计方向","再确认纹样来源与授权","最终完成生产级交付"][revenueStep]}</h3></div></div><div className="journey-nav">{[["AI设计订阅","持续生成包装、文案与展示方向。"],["纹样商业授权","方案正式商用时购买对应授权。"],["设计师精修","复杂项目升级为生产级设计交付。"]].map((x,i)=><button className={revenueStep===i?"active":""} key={x[0]} onClick={()=>setRevenueStep(i)}><span>0{i+1}</span><div><b>{x[0]}</b><small>{x[1]}</small></div><ArrowRight/></button>)}</div></div><div className="ecosystem"><div className="role seller"><small>需求与订单</small><b>跨境卖家</b><p>获得低成本、完整的文化包装方案</p></div><div className="role inheritor"><small>纹样资料与授权</small><b>传承人与文化机构</b><p>获得规范传播与授权收益入口</p></div><div className="platform-node"><span>纹</span><b>纹脉平台</b><small>设计 × 文化 × 商业</small></div><div className="role designer"><small>专业精修服务</small><b>设计师</b><p>承接经过筛选的高价值设计需求</p></div></div></div></section>
  <section className="roadmap-section"><div className="section"><Head index="07" kicker="ROADMAP" title="从概念原型，走向真实设计平台" copy="明确当前完成度与下一步建设内容，让产品愿景和落地路径同时可见。"/><div className="roadmap"><article className="now"><span>当前阶段</span><h3>产品概念原型</h3><p>完成定位、商业模式、页面结构与核心流程演示。</p></article><article><span>下一阶段</span><h3>非遗数字库＋AI工具链</h3><p>建设纹样、传统色和故事资料，接入包装生成能力。</p></article><article><span>长期阶段</span><h3>授权与设计服务生态</h3><p>连接卖家、传承人、设计师与包装供应链。</p></article></div></div></section>
  <section className="section faq"><Head index="08" kicker="QUESTIONS" title="开始之前，你可能想知道" copy=""/>{[["生成的设计可以直接印刷吗？","当前原型展示设计方向。正式印刷前，需要完成尺寸、出血、字体、色彩模式与材料工艺检查。"],["平台推荐的纹样都能直接商用吗？","不能一概而论。正式产品会分别标注纹样来源、授权主体、使用范围和期限。"],["合规提示是否等同于法律审核？","不是。平台用于辅助筛查和整理风险线索，不替代目标市场的专业法律与标签合规审核。"]].map((f,i)=><article key={f[0]}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{f[0]}</span><ChevronDown className={openFaq===i?"open":""}/></button>{openFaq===i&&<p>{f[1]}</p>}</article>)}</section>
  <section className="closing"><p className="kicker light">START WITH ONE PRODUCT</p><h2>从一件中国商品开始，生成它面向世界的新表达。</h2><p>体验“上传产品—选择市场—匹配非遗—生成完整方案”的核心流程。</p><button className="gold" onClick={()=>document.querySelector("#creator")?.scrollIntoView({behavior:"smooth"})}>体验茶叶示例 <ArrowRight/></button></section>
  <footer><a className="brand" href="#top"><span>纹</span><b>纹脉<small>WENMAI</small></b></a><p>面向中小跨境电商卖家的非遗包装AI设计平台</p><div><a href="#why">产品能力</a><a href="#patterns">纹样库</a><a href="#business">商业模式</a></div><small>© 2026 纹脉 · 当前页面为结构化概念原型</small></footer>
 </main>
}
function Media({label,detail,className=""}:{label:string;detail:string;className?:string}){const src=label.includes("首页主视觉")?"/wenmai-hero-export-transformation.png":label.includes("AI与设计师")?"/wenmai-ai-human-workflow.png":label.includes("包装完整")?"/wenmai-us-japan-comparison.png":label.includes("产品上传")?"/wenmai-packaging.webp":label.includes("市场选择")?"/wenmai-us-japan-comparison.png":label.includes("纹样推荐")?"/hero-archive.webp":label.includes("完整方案输出")?"/hero-packaging.webp":label.includes("纹样图 1")?"/hero-archive.webp":label.includes("纹样图 2")?"/hero-digital.webp":label.includes("纹样图 3")?"/hero-packaging.webp":"";return <div className={`media-placeholder has-image ${className}`} role="img" aria-label={label}>{src&&<img src={src} alt={label}/>}<div className="image-shade"/><b className="image-label">{label}</b><span className="image-note">{detail}</span></div>}
function Feature({icon:Icon,title,copy}:{icon:React.ElementType;title:string;copy:string}){return <article className="feature"><Icon/><h3>{title}</h3><p>{copy}</p><ArrowRight/></article>}
function Head({index,kicker,title,copy}:{index:string;kicker:string;title:string;copy:string}){return <div className="section-head"><div><span>{index}</span><p>{kicker}</p></div><h2>{title}</h2>{copy&&<p className="section-copy">{copy}</p>}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
